### ISSUE TITLE
Joomla 5 compatibility and forum access

### ISSUE THREAD

**Issue by mgscreativa** [J2Store4/j2store4#62]
Hi! is J2Store 4.0.4 compatible with Joomla 5?

Where can I access J2Store support forum?

Thanks!

**Comment by newlinewebdesign** [comment]
I am using 4.0.4 on multiple 5.0 and 5.1 sites without issue

**Comment by mgscreativa** [comment]
Cool! I also tested it in J5 but I wanted to be certain.

**Comment by mgopin3** [comment]
I understand your concern. Currently, we have not tested J2Store 4 compatibility with Joomla 5. Please rest assured that we appreciate your feedback, and we will take note of it. In the near future, we plan to migrate and conduct thorough testing to ensure J2Store 4 is compatible with Joomla 5. This update will be included in an upcoming J2Store release. Thank you for your patience and understanding.

**Comment by mgopin3** [comment]
@mgscreativa We believe the reported issue has been addressed. Could you please confirm that the problem is resolved on your end? If everything looks good, we'll go ahead and close this issue.

If you have any further questions or if there's anything else you'd like assistance with, please don't hesitate to let us know. We appreciate your feedback!

**Comment by mgscreativa** [comment]
Yes, it seems to be working
