### ISSUE TITLE
Override for bootstrap

### ISSUE THREAD

**Issue by webgras** [J2Store4/j2store4#67]
I am on J2store 4.0.4 with J4.4.1
I want to override a file in the bootstrap 5 plugin, but overrides for the plugin are not working.

Original file:
/plugins/j2store/app_bootstrap5/app_bootstrap5/tmpl/bootstrap5/default.php

My override:
/templates/MYTEMPLATE/html/plg_j2store_app_bootstrap5/bootstrap5/default.php

but it is not working.

Expected behaviour:
File can be overriden.

**Comment by mgopin3** [comment]
I understand your concern. Upon reviewing the issue you mentioned, we identified that there is an incorrect template override path on your site. To address this, I recommend following the correct template override path for the **bootstrap5/default.php** file. 

Here is the accurate template override path: 
**/templates/YOUR-TEMPLATE/html/com_j2store/templates/bootstrap5/default.php**

After creating this path on your site, the template override should function seamlessly without any issues. If you encounter any further difficulties, please feel free to reach out, and we will assist you promptly

**Comment by mgopin3** [comment]
@webgras We believe the reported issue has been addressed. Could you please confirm that the problem is resolved on your end? If everything looks good, we'll go ahead and close this issue.

If you have any further questions or if there's anything else you'd like assistance with, please don't hesitate to let us know. We appreciate your feedback!

**Comment by webgras** [comment]
Yes, it works now. Thanks!
