### ISSUE TITLE
Problem in the option section of the j2store

### ISSUE THREAD

**Issue by sajadsheikhy** [J2Store4/j2store4#97]
**Suppose we have defined several options and used this option in 100 products for example**
For some reasons, we are going to disable this option in all products and enable it at another time. Pay attention, disable and not edit
We will have two ways:
**1-**100 products one by one and remove that option
**Problem:** It takes a lot of time and you have to edit 100 products again to activate it again
2- Disabling the option for the time we need
### Note: I think we have a bug here
By deactivating the option, the option is disabled in the options manager, but it can still be displayed in all products that have been used.
**For the information of the j2store's strong team**
![Uploading 2.png…]()

**Comment by sajadsheikhy** [comment]
![2](https://github.com/J2Store4/j2store4/assets/147089574/f2b2a5f7-74b7-4577-aaf8-9f7126397568)
![1](https://github.com/J2Store4/j2store4/assets/147089574/7d998bd7-0bdf-4d1c-b8fe-bc968762d776)

**Comment by mgopin3** [comment]
@sajadsheikhy I completely understand your concern. In order to disable the option for a product, it's necessary to individually deactivate it for each product and manually update the respective information. Typically, product options are displayed from the database, meaning that disabling options through J2store's interface at Catalog > Options won't universally affect all products. Each product will require individual attention for this task. We appreciate your understanding in this matter.

Note:- Before submitting a report on issue tracker https://github.com/J2Store4/j2store4/issues/60, please review the provided instructions, as they specify the types of issues for which we can offer support. Issues outside the scope of these instructions will not be considered. We appreciate your understanding.

**Comment by sajadsheikhy** [comment]
hi
Please guide me how I can disable or delete an option in general from the database so that it is disabled in all products
God bless you

**Comment by mgopin3** [comment]
@sajadsheikhy When creating options for a product, it is common practice to store the product options in different tables such as '**product_options**', '**product_optionvalues**', and '**optionvalues**', utilizing the product ID. As a result, directly deleting the product option from the database is not recommended as it involves dependencies across multiple tables. It is advisable to follow proper procedures and mechanisms provided by the system or application to manage product options effectively. Therefore, In this case, I suggest you manually disable the product options and save the changes.
Hope you understand.

**Comment by mgopin3** [comment]
@sajadsheikhy Thankyou for your understand and patience.
we will consider your requirement as feedback, and we will incorporate it into our upcoming J2Store release. If everything looks good, we'll go ahead and close this issue.

If you have any further questions or if there's anything else you'd like assistance with, please don't hesitate to let us know. We appreciate your feedback!
